# Generated by Django 3.0.4 on 2020-03-19 23:20

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='-1.0, -1.0', max_length=63),
        ),
    ]
